language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2

matrix:
    include:
        - php: 7.1
          env: DEPENDENCIES=dev
        - php: 5.5
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'

before_install:
    - composer self-update
    - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;

install: composer update --prefer-dist $COMPOSER_FLAGS

script: ./vendor/bin/phpunit